kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: setup-ci
    image: autonomy/build-container:latest
    commands:
      - git fetch --tags
      - install-ci-key
      - setup-buildx-amd64-arm64
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx

  - name: build-dry-run
    image: autonomy/build-container:latest
    pull: always
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx
    commands:
      - docker buildx build -f Dockerfile -t autonomy/build-container .
    when:
      event:
        - pull_request

  - name: build-and-push
    image: autonomy/build-container:latest
    pull: always
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}"
      - docker buildx build -f Dockerfile -t autonomy/build-container --push .
    when:
      event:
        exclude:
          - pull_request

volumes:
  - name: docker-socket
    host:
      path: /var/ci-docker
  - name: docker
    temp: {}

---
kind: pipeline
name: notify
type: kubernetes

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
